### ISSUE TITLE
Missing Variable Names in Documentation

### ISSUE THREAD

**Issue by nstr10** [rapid7/vm-console-client-python#11]
There may be other examples, but at least in the VulnerabilityExceptionApi docs there are variables with names like `param1` and `param2` with no information about what they are, what they're for, etc.

Are these extraneous? Can they be ignored?

### Other relevant information
https://github.com/rapid7/vm-console-client-python/blob/master/docs/VulnerabilityExceptionApi.md

**Comment by zyoutz-r7** [comment]
Early in the release of the swagger definition there were unnamed variables which resulted in these parameters.  With the more recent releases of the client these parameters can now be referenced based on the fields defined on each model.
