### ISSUE TITLE
api files are multiple versions behind

### ISSUE THREAD

**Issue by KoalaTea** [rapid7/vm-console-client-python#12]
generating the code locally to fix the python 3.7 issue leads to issues in newer versions of insightvm. for instance SonarCriterion has a property of "searchDomain" which has been changed to just "domain" somewhere between 6.5.19 and 6.5.35, this information is also incorrect in the official documentation at https://help.rapid7.com/insightvm/en-us/api/index.html#operation/updateSonarQuery

### Other relevant information

python 3.7
api-file console-swagger-6.5.19.json
swagger version 2.3.1

**Comment by zyoutz-r7** [comment]
@KoalaTea The Swagger file from release 6.5.41 has recently been used to generate the latest client.  This also has an intermediate change to support Python 3.7 as Codegen has not been updated/released for the async reservation.

As for searchDomain for Sonar, I would recommend leveraging your console's swagger file at `/api/3/html` (`/api/3/json`).  This should show the filter for the criteria as searchDomain with the latest version.
