### ISSUE TITLE
Configuration object missing attribute: safe_chars_for_path_param

### ISSUE THREAD

**Issue by myfoostrong** [rapid7/vm-console-client-python#19]
Not sure if this is just user error or not, but hitting a bug when running calls with parameters. Non-parameter requests (like get_assets, get_scans, etc.) work fine, but there's an AttributeError whenever parameters are required.

I'm taking the sample script 'samples/list_assets.py' and changing the API call to the singular 'get_asset'. i.e. line 32 is now:
`assets = asset_api.get_asset(5)`

### Expected Behavior
To get the data on the asset with ID '5'
i.e.
```
{'addresses': [{'ip': '192.168.X.X', 'mac': 'XX:XX:0F:XX:XX:18'}],
 'assessed_for_policies': False,
...
```

### Actual Behavior
Error encountered accessing a value in the Configuration object.

```
Traceback (most recent call last):
  File "C:/Users/user/dev/vm-console-client-python/samples/run_scan.py", line 43, in <module>
    api_response = api_instance.get_asset(5)
  File "C:\Users\user\dev\vm-console-client-python\rapid7vmconsole\api\asset_api.py", line 474, in get_asset
    (data) = self.get_asset_with_http_info(id, **kwargs)  # noqa: E501
  File "C:\Users\user\dev\vm-console-client-python\rapid7vmconsole\api\asset_api.py", line 552, in get_asset_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\user\dev\vm-console-client-python\rapid7vmconsole\api_client.py", line 320, in call_api
    _preload_content, _request_timeout)
  File "C:\Users\user\dev\vm-console-client-python\rapid7vmconsole\api_client.py", line 120, in __call_api
    quote(str(v), safe=config.safe_chars_for_path_param)
AttributeError: 'Configuration' object has no attribute 'safe_chars_for_path_param'
```

### Possible Solution
An empty string is defined in the Configuration __init__ function, (rapid7vmconsole/configuration.py:100)

Setting an empty string for the config object in the main script, fixes the problem (samples/list_assets.py:16)
```
...
config.key_file = None
config.safe_chars_for_path_param = ''
```

### Steps to Reproduce (for bugs)
As stated above, simply provide a valid user, password, and server address, then change the request function from get_assets() to get_asset({id}), where id is a valid asset ID

Python code that reproduces the issue:
```
import rapid7vmconsole
import base64
import logging
import sys

config = rapid7vmconsole.Configuration(name='Rapid7')
config.username = 'nxadmin'
config.password = 'nxpassword'
config.host = 'https://localhost:3780'
config.verify_ssl = False
config.assert_hostname = False
config.proxy = None
config.ssl_ca_cert = None
config.connection_pool_maxsize = None
config.cert_file = None
config.key_file = None

# Logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.INFO)
logger.addHandler(ch)
config.debug = False


auth = "%s:%s" % (config.username, config.password)
auth = base64.b64encode(auth.encode('ascii')).decode()
client = rapid7vmconsole.ApiClient(configuration=config)
client.default_headers['Authorization'] = "Basic %s" % auth
asset_api = rapid7vmconsole.AssetApi(client)
assets = asset_api.get_asset(5)

for a in assets.resources:
    print("Asset ID: %s; Hostname: %s; IP Address: %s" % (a.id, a.host_name, a.ip))

```

### Your Environment
* Library version or repository branch: master, pulled 2/12/2019
* Python version: tested on 2.7 and 3.7, venv
* Operating System and version: Windows 10 x64, PyCharm Community venv
* InsightVM/Nexpose product version:

**Comment by tschmidtke-r7** [comment]
Hi @myfoostrong, thanks for submitting this issue! The possible solution you provided is what I recommend. I am going to close this, but will see about adding additional details setting up an ApiClient object this to the README.
