### ISSUE TITLE
How to create console generated shared secret key?

### ISSUE THREAD

**Issue by houseofcoder** [rapid7/vm-console-client-python#22]
We need to pair Engine to Console (Reverse) for that we need to generate shared secret key but we don't want to do it from UI rather we want it to be generated programmatically.

I already went through InsightVM/Nexpose API V3 documentation there is no API available to achieve what we want to do.

This [nexpose-client](https://github.com/rapid7/nexpose-client) library has the feature to generate shared secret key but it's **Deprecated**

Is there anyway by with we can generate shared secret key apart from Nexpose UI?

**Comment by tschmidtke-r7** [comment]
Hi, thanks for asking about this!

The V3 API does have the capability to generate shared secrets as of a more recent release than the public documentation currently covers. To access the most recent version of the documentation, I recommend logging into your Security Console and access the documentation generated by it. 

This can be done by clicking the '?' menu in the top menu bar and clicking 'API Documentation':
![image](https://user-images.githubusercontent.com/26392344/65517332-23eb3580-dea8-11e9-92b8-3585db53e4a3.png)

You should see the following details:
![image](https://user-images.githubusercontent.com/26392344/65517514-74629300-dea8-11e9-989c-9fb79f2407ba.png)
![image](https://user-images.githubusercontent.com/26392344/65517618-a673f500-dea8-11e9-96db-4e0052ee9e85.png)
![image](https://user-images.githubusercontent.com/26392344/65517551-86443600-dea8-11e9-977c-ac8634634118.png)
![image](https://user-images.githubusercontent.com/26392344/65517643-b390e400-dea8-11e9-9be8-50a27d7d6334.png)
![image](https://user-images.githubusercontent.com/26392344/65517675-bee40f80-dea8-11e9-8907-1e6fb50cf8f2.png)

**Comment by houseofcoder** [comment]
Ohhh it's visible only when i navigate to API Doc from Nexpose console.

It's not available here 
https://help.rapid7.com/insightvm/en-us/api/index.html

Thanks a lot :+1:
