### ISSUE TITLE
Most recent release whl file doesn't match release notes

### ISSUE THREAD

**Issue by emartin-merrill-r7** [rapid7/vm-console-client-python#23]
## Issues and Contributing
whl file version 1.0.0_6.5.50 does not match source code - ScanEngineApi in whl is missing the create_shared_secret functions but they are present in the source code zip attached

### Expected Behavior
engineApi = rapid7vmconsole.ScanEngineApi(client)
engineApi.create_shared_secret()
results in a pairing key being generated and returned

### Actual Behavior
returns AttributeError: 'ScanEngineApi' object has no attribute 'create_shared_secret'

### Possible Solution
regenerate whl file from sources

### Steps to Reproduce (for bugs)
download whl file from releases page: https://github.com/rapid7/vm-console-client-python/releases/download/1.0.0-6.5.50/rapid7_vm_console-1.0.0_6.5.50-py2.py3-none-any.whl
install with pip
try and get a pairing key with create_shared_secret()

### Your Environment
* multiple: python2/3, windows/mac/linux

**Comment by zyoutz-r7** [comment]
Latest wheel has been generated based off of the InsightVM 6.6.55 swagger definition. Closing issue as this has been resolved with more recent releases.
