### ISSUE TITLE
Generating report issue

### ISSUE THREAD

**Issue by dirtcrosser** [rapid7/vm-console-client-python#25]
## Issues and Contributing

Whenever I try to generate a report using API. It seems the "generating" report status is not working. It looks like its generating the report, but its taking way too much longer compare to manually running the report.

### Steps to Reproduce (for bugs)

Python code that reproduces the issue:
def generate_report():
    api_instance = rapid7vmconsole.ReportApi(client)
    id = getreportid.var  # int | The identifier of the report.
    api_response = api_instance.generate_report(id)
    print(api_response)
    print("Generated Report")

the script above triggers the generation of the report but the task is not being completed.

### Your Environment
* Library version or repository branch:
* Python version: 3
* Operating System and version:
* InsightVM/Nexpose product version:
Nexpose Product 6.5.96

**Comment by zyoutz-r7** [comment]
@dirtcrosser When generating reports, it will likely take some time for the data model to be built and the content generated.  The recommended workflow would be to:
1. Create the report config
2. Generate the report
3. Check the status of the report (poll every 60 seconds or so)
4. Download report when status == "Complete"

A similar process can be found in the following sample: https://github.com/rapid7/vm-console-client-python/blob/master/samples/generate_sql_report.py.  The only response when `generate_report` is called will be the report instance ID: 
![Screen Shot 2020-01-22 at 11 18 06 PM](https://user-images.githubusercontent.com/20776497/72956267-1fa72a00-3d6d-11ea-9737-57b79532e3cf.png)

Hope that helps!

**Comment by zyoutz-r7** [comment]
Closing stale issue as the sample provided is the project has been confirmed to work.  Anther reason it could be taking longer than expected is because it is polling for results and there is a 30 second sleep before each report status check.
