### ISSUE TITLE
Report - Scope - Select Site - how to select/tick option to Use only assets found in the last scan

### ISSUE THREAD

**Issue by dirtcrosser** [rapid7/vm-console-client-python#26]
## Issues and Contributing

Would like to know how can I select the option to "Use only assets found in the last scan" when using the API. Can you share the code if ever? I cant find any settings under the Report.api or in ReportConfigScopeResource 

### Steps to Reproduce (for bugs)

Python code that reproduces the issue:
```python
print("this is only an example Python code block")
```

### Your Environment
* Library version or repository branch:
* Python version:
* Operating System and version:
* InsightVM/Nexpose product version:

**Comment by tschmidtke-r7** [comment]
It doesn't look like this made it to the documentation. That said, the option is available attribute on the scope of a report, so something like the following would work:

```
scope = {
    "sites": [2],
    "assetsInOnlyMostRecentScanOfSite": True
}
report_config = rapid7vmconsole.Report(name=report_name, format='sql-query', query=sql, version='2.3.0', scope=scope)
response = client.create_report(report=report_config)
```

**Comment by dirtcrosser** [comment]
thanks tschmidtke-r7! it works.

**Comment by dirtcrosser** [comment]
Also maybe you can assist in issue#25.  this is somehow part of the code that I'm currently working. :) appreciate the assistance.

**Comment by zyoutz-r7** [comment]
Thanks for the update @dirtcrosser, glad that helped.  Responded on the other issue and will close this out.
