### ISSUE TITLE
Just checking if this API works with a Site configured with AWS Asset Sync discovery connection

### ISSUE THREAD

**Issue by dirtcrosser** [rapid7/vm-console-client-python#28]
## Issues and Contributing

This is just a general inquiry and to check if there is a limitation in the API.

### Actual Behavior

I have a script to check the scan status but looks like its not returning the status. I tested the script using a AWS connection (Legacy) and this works fine.

### Steps to Reproduce (for bugs)

Python code that reproduces the issue:
            scanstatus = api_instance.get_scan(scansessionid)
            print(scanstatus)
            scanstate = scanstatus.status
            print(scanstate)
            while scanstate != 'finished':
                scanstatus = api_instance.get_scan(scansessionid)
                scanstate = scanstatus.status
                print("still scanning")
                time.sleep(300)
            else:
                print("done scanning")
                print(scanstate)

### Your Environment
* Library version or repository branch:
* Python version: 3.8
* Operating System and version: Windows Server 2012
* InsightVM/Nexpose product version: NExpose 6.6.8

**Comment by tschmidtke-r7** [comment]
Hi @dirtcrosser, I'm not aware of any inherent limitations. I'd recommend raising this as an issue with support so that further investigation can be done: https://www.rapid7.com/for-customers/
