### ISSUE TITLE
create_asset api call adds inactive assets to the site

### ISSUE THREAD

**Issue by abhaykrp** [rapid7/vm-console-client-python#32]
Hi,

I have been trying to add new asset using `create_asset` API call Ref: https://github.com/rapid7/vm-console-client-python/blob/master/docs/AssetApi.md#create_asset

Code :  
```
hostname = rapid7vmconsole.HostName('ec2-<ip>.compute-1.amazonaws.com')
asset = rapid7vmconsole.AssetCreate(_date='2020-05-20',host_name=hostname,ip='<IP>')
api_response = asset_api.create_asset(id, asset=asset)
```
The asset gets created but is an inactive asset. 

Is it expected? How do we resolve this?

**Comment by gschneider-r7** [comment]
This is because "active" assets count is based on the last scan of a site. Since this API creates an asset without a scan it will not be counted as active.

**Comment by zyoutz-r7** [comment]
Closing based on the response by @gschneider-r7. As he mentioned the asset will only be listed as active once a scan has occurred.
