### ISSUE TITLE
After ISVM update to 6.6.68: Model configuration.py raises error when retrieving all assets

### ISSUE THREAD

**Issue by PNO2020** [rapid7/vm-console-client-python#40]
When calling <..>/rapid7vmconsole/api/asset_api.py" an error is raised in line 2081 (get_assets).

Digging deeper the error is raised in:

<..>/rapid7vmconsole/models/configuration.py", line 73, in name
    raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

The raised error is:
ValueError: Invalid value for `name`, must not be `None`

### Expected Behavior
Getting all assets from the ISVM server

### Actual Behavior
Error is raised and python script end with raised error

### Possible Solution
Can't figure out way this happens. Everything worked before the update to version 6.6.68

### Steps to Reproduce (for bugs)
Get all assets from ISVM server using the API

Python code that reproduces the issue:
Base code:

def get_assets(client):
  assetapi = rapid7vmconsole.AssetApi(client)
  
  page = 0
  all_assets = []
  while True:
    result = assetapi.get_assets(page=page, size=500)
    if not result.resources:
      break
    all_assets.extend(result.resources)
    if len(all_assets) >= result.page.total_resources:
      break
    page = page + 1
  
  return all_assets

### Your Environment
ISVM server: Redhat Unix
Aprox. 50000 assets
12 remote scan engines

### Other relevant information
Need some expert advice.

**Comment by crypticraven** [comment]
It seems to be failing on more than just the assets API. It's failing for me on Users, exceptions, vulnerabilities....

**Comment by PNO2020** [comment]
After some experimenting, we were able to solve this issue by commenting out the lines with 'raise ValueError("Invalid value for name, must not be None") # noqa: E501'.
Seems to work now, and no other issues reported concerning 'Users', 'Exceprtions', ...
We are thinking of not using API call's altogether anymore, it's just not stable enough.

**Comment by cturner-confluent** [comment]
Just came across this issue as well. Seems to me that since there are to Configuration classes imported in __init__ seems we might not have the right one... but not sure if thats right going to test your fix above and see what happens.
