### ISSUE TITLE
asset search fails when user group contains a name of "None"

### ISSUE THREAD

**Issue by dgarozzo** [rapid7/vm-console-client-python#41]
## Issues and Contributing

Attempting to do a search for any assets with a matching host-name, but getting an exception.

### Expected Behavior

Possibly allow "None" as a value? Is there a way to tell the difference between the string "None" and the value None?

### Actual Behavior

Exception thrown:
  File "/usr/local/lib/python2.7/site-packages/rapid7vmconsole/models/configuration.py", line 73, in name
    raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

### Possible Solution

I ended up commenting out the if block that checks to make sure name is not None.

### Steps to Reproduce (for bugs)

json return value includes:
 {
      "id" : 513,
      "name" : "None"
    }

Python code that reproduces the issue:
```python
print("this is only an example Python code block")
```

### Your Environment
* Library version or repository branch:
* Python version: 2.7
* Operating System and version: Linux
* InsightVM/Nexpose product version:

**Comment by jamesvc3** [comment]
Same thing here, other versions of python.  
Workaround mentioned above worked.
Linux python version:  3.6.
Windows python version 3.8.
InsightVM.

**Comment by ScottMnemonic** [comment]
Confirming the issue and workaround as well. This error did not appear until either the Feb 17th or Feb 24th release updates, v6.6.67 did not have this issue.

Commenting out these lines (which @dgarozzo mentioned) restored functionality for me:
https://github.com/rapid7/vm-console-client-python/blob/master/rapid7vmconsole/models/configuration.py#L72-L73

**Comment by BinkyWong** [comment]
I can also confirm the issue and workaround.

**Comment by BeanBagKing** [comment]
Confirming the same. Not sure if it was necessary, but I ran setup.py build and install after as well.

**Comment by SaltyGrandpa** [comment]
It looks like this is because the find_assets and find_assets_with_http_info methods do not respect the ApiClient specified when you create your AssetApi. Commenting out the None type exception does work, but I don't think solves the root of the problem. But, nevertheless, that's what I'm doing for now as well :)
