### ISSUE TITLE
not able to understand api_client.py file please help me understand please

### ISSUE THREAD

**Issue by ujjawalmaheshwari** [rapid7/vm-console-client-python#42]
### Steps to Reproduce (for bugs)

Python code that reproduces the issue:
```python
print("this is only an example Python code block")
```

### Your Environment
* Library version or repository branch:
* Python version:
* Operating System and version:
* InsightVM/Nexpose product version:

**Comment by zyoutz-r7** [comment]
@ujjawalmaheshwari Have you attempted any of the samples that have been provided here: https://github.com/rapid7/vm-console-client-python/blob/master/samples/list_assets.py. This should give a decent starting point

**Comment by ujjawalmaheshwari** [comment]
sir are you free please sir
i need just one google meet i will be highly grateful if this meet happens please sir

**Comment by ujjawalmaheshwari** [comment]
Sir I know  am asking for a lot but please sir help me with this .

**Comment by ujjawalmaheshwari** [comment]
Is it possible Sir? Please just few minutes time would be more then enough I am not able to understand why sanitize_for_serialization and deserialize and few other functions are used please sir help me get the concept. Thanking you for the same

**Comment by shubhamyh** [comment]
@zyoutz-r7 sir please tell me why rapid7vmconsole.Configuration(name='Rapid7') Rapid7 is used please sir
